

const Projects = () => {
    return (
        <div id="projects"> {/* Asegúrate de que el id sea minúsculo y coincida con el href del botón */}
            <h2>projects</h2>
            {/* Contenido de la sección de Contact */}
            <p>Aquí va el contenido de projects.Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, sit ab corrupti, ullam culpa, vel ea nihil eveniet qui quos quisquam enim porro. Eos eligendi architecto sint laboriosam sapiente ipsam!</p>
        </div>
    )
}

export default Projects;